services:
  backend:
    image: ghcr.io/bakseter/spenn/backend:latest
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=database
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DEV=true
    depends_on:
      database:
        condition: service_healthy
    links:
      - database
    develop:
      watch:
        - action: sync
          path: ./static
          target: /app/static
        - action: sync
          path: ./templates
          target: /app/templates
        - action: rebuild
          path: '**/*.go'
          target: /app

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

