apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spenn
  namespace: spenn
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: spenn
  endpoints:
    - port: http
