apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: spenn-database
  namespace: spenn
spec:
  instances: 3
  inheritedMetadata:
    labels:
      recurring-job.longhorn.io/source: enabled
      recurring-job-group.longhorn.io/hetzner-backup: enabled
  affinity:
    nodeSelector:
      node.longhorn.io/create-default-disk: 'true'
    enablePodAntiAffinity: true
    topologyKey: bakseter.net/physical-node
    podAntiAffinityType: required
  storage:
    size: 2Gi
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 1Gi
